version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - UVICORN_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    depends_on:
      neo4j:
        condition: service_healthy

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: ["sh", "-c", "npm --version >/dev/null 2>&1 && tail -f /dev/null"]
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  neo4j:
    image: neo4j:5-community
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./neo4j/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo4jpassword", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  neo4j_data:
